"""
SQLite database setup and connection helpers for Kime.

Schema
------
jobs
    Tracks the lifecycle (pending → processing → complete | failed) of an
    upload-and-analyse request.

scores
    Stores per-job scoring results, per-criterion metric deltas (JSON), and
    the coaching feedback generated by the Claude API.
"""

import os
import sqlite3
from pathlib import Path

# Allow the DB path to be overridden via env var (useful in tests and Docker).
_default_db_path = Path(__file__).parent.parent / "kime.db"
DB_PATH: str = os.environ.get("KIME_DB_PATH", str(_default_db_path))

_SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    id          TEXT PRIMARY KEY,
    status      TEXT NOT NULL DEFAULT 'pending',
    technique   TEXT,
    video_path  TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scores (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id        TEXT    NOT NULL REFERENCES jobs(id),
    technique     TEXT    NOT NULL,
    -- JSON blob: {"metric_name": {"user": …, "reference": …, "delta": …}, …}
    criteria      TEXT    NOT NULL DEFAULT '{}',
    overall_score REAL,
    feedback      TEXT,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""


def get_connection(db_path: str = DB_PATH) -> sqlite3.Connection:
    """Return an open :class:`sqlite3.Connection` with ``Row`` factory set.

    Args:
        db_path: Path to the SQLite database file.  Defaults to ``DB_PATH``.
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    # Enforce foreign-key constraints.
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db(db_path: str = DB_PATH) -> None:
    """Create all tables (idempotent — safe to call on every startup).

    Args:
        db_path: Path to the SQLite database file.  Defaults to ``DB_PATH``.
    """
    with get_connection(db_path) as conn:
        conn.executescript(_SCHEMA)
