/**
 * A single per-criterion score returned by the judging engine.
 */
export interface CriterionScore {
  /** Human-readable label, e.g. "Chamber Height" */
  label: string;
  /** 0–100 score for this criterion */
  score: number;
}

/**
 * A completed analysis attempt as returned by GET /api/attempts/:id.
 */
export interface Attempt {
  id: string;
  technique: string;
  /** Overall 0–100 score */
  overall_score: number;
  /** One-word or short label, e.g. "Good", "Needs Work", "Excellent" */
  technique_label: string;
  /** Per-criterion scores used to render the radar chart */
  criterion_scores: CriterionScore[];
  /** Plain-language coaching prose generated by Claude */
  coaching_feedback: string;
  /** False when the camera angle is likely to cause mis-scoring */
  camera_angle_ok: boolean;
  /** ISO-8601 timestamp */
  created_at: string;
  /** "pending" | "processing" | "completed" | "failed" */
  status: string;
}
