import type { FrameLandmarks } from '../components/SkeletonOverlay';

/**
 * A single per-criterion score returned by the judging engine.
 */
export interface CriterionScore {
  /** Human-readable label, e.g. "Chamber Height" */
  label: string;
  /** 0–100 score for this criterion */
  score: number;
}

/**
 * A completed analysis attempt as returned by GET /api/attempts/:id.
 */
export interface Attempt {
  id: string;
  technique: string;
  /** Overall 0–100 score */
  overall_score: number;
  /** One-word or short label, e.g. "Good", "Needs Work", "Excellent" */
  technique_label: string;
  /** Per-criterion scores used to render the radar chart */
  criterion_scores: CriterionScore[];
  /** Plain-language coaching prose generated by Claude */
  coaching_feedback: string;
  /** False when the camera angle is likely to cause mis-scoring */
  camera_angle_ok: boolean;
  /** ISO-8601 timestamp */
  created_at: string;
  /** "pending" | "processing" | "completed" | "failed" */
  status: string;
  /** Relative or absolute URL to the uploaded video file. Optional. */
  video_url?: string;
  /**
   * Per-frame MediaPipe pose landmarks (33 landmarks per frame).
   * Absent when the analysis job hasn't completed yet or landmark
   * storage is disabled.
   */
  landmark_frames?: FrameLandmarks[];
  /**
   * Frames-per-second of the landmark data.
   * Used to map `video.currentTime` → frame index.
   * Defaults to 30 when absent.
   */
  landmark_fps?: number;
}
