"""Build data/sources.yaml from yt-dlp search candidates (Phase 2 helper).

Reads data/candidates.json (written by the search step), drops manually
excluded video IDs, optionally backfills a technique with an extra search,
and writes the sources.yaml consumed by ``python -m data_pipeline.cli fetch``.
"""
from __future__ import annotations

import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).parent.parent
YTDLP = str(ROOT / ".venv" / "bin" / "yt-dlp")

# Manually excluded: wrong technique that automated filters cannot catch.
EXCLUDE = {
    "5r0kY_lXGcw",  # 720-degree spinning kick breaking demo, not a front kick
    "4e_P4ei0Khw",  # jump front kick (different technique variant)
    "vFVL81miTgQ",  # jump front kick (different technique variant)
}

BACKFILL_QUERY = "front kick slow motion technique karate"
BACKFILL_TECH = "front_kick"
BACKFILL_TARGET = 12


def main() -> None:
    with open(ROOT / "data" / "candidates.json") as f:
        cands = json.load(f)

    cands = {t: [c for c in cs if c["id"] not in EXCLUDE] for t, cs in cands.items()}
    seen = {c["id"] for cs in cands.values() for c in cs}

    if len(cands[BACKFILL_TECH]) < BACKFILL_TARGET:
        out = subprocess.run(
            [YTDLP, "--no-warnings", "--flat-playlist", "-J",
             f"ytsearch6:{BACKFILL_QUERY}"],
            capture_output=True, text=True, timeout=180,
        )
        if out.returncode == 0:
            for e in json.loads(out.stdout).get("entries") or []:
                vid, dur = e.get("id"), e.get("duration")
                title = e.get("title") or ""
                if (vid and vid not in seen and dur and 8 <= dur <= 240
                        and "jump" not in title.lower()
                        and "spin" not in title.lower()):
                    cands[BACKFILL_TECH].append(
                        {"id": vid, "duration": dur, "title": title})
                    seen.add(vid)
                    if len(cands[BACKFILL_TECH]) >= BACKFILL_TARGET:
                        break

    lines = [
        "# data/sources.yaml — candidate clips for the Phase 2 data pipeline.",
        "# Generated by scripts/build_sources.py from yt-dlp search results "
        "(2026-06-12).",
        "# Usage: python -m data_pipeline.cli fetch --sources data/sources.yaml",
        "",
    ]
    for tech, cs in cands.items():
        lines.append(f"{tech}:")
        for c in cs:
            title = c["title"].replace("\n", " ")[:70]
            lines.append(f"  # {int(c['duration'])}s — {title}")
            lines.append(f"  - https://www.youtube.com/watch?v={c['id']}")
        lines.append("")

    (ROOT / "data" / "sources.yaml").write_text("\n".join(lines))
    print("Wrote data/sources.yaml:")
    for tech, cs in cands.items():
        print(f"  {tech}: {len(cs)} candidates")


if __name__ == "__main__":
    main()
